services:
  mlflow:
    image: salahgo/mlflow:v4
    container_name: mlflow
    working_dir: /mlflow
    command: >
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --artifacts-destination s3://mlflow/mlflow-artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflowdata:/mlflow
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio12345
      AWS_SESSION_TOKEN: ""
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000

  zenml-db:
    image: mysql:8.0
    container_name: zenml-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: zenmlroot
      MYSQL_DATABASE: zenml
      MYSQL_USER: zenml
      MYSQL_PASSWORD: zenmlpass
    volumes:
      - zenmlmysqldata:/var/lib/mysql

  zenml-server:
    image: zenmldocker/zenml-server:latest
    container_name: zenml-server
    restart: unless-stopped
    depends_on:
      - zenml-db
    ports:
      - "8080:8080"
    environment:
      ZENML_STORE_URL: mysql://zenml:zenmlpass@zenml-db:3306/zenml
      ZENML_DEFAULT_USER_NAME: admin
      ZENML_DEFAULT_USER_PASSWORD: zenml
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":4545"
    ports:
      - "9000:9000"   # S3 API
      - "4545:4545"   # Console Web
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    volumes:
      - ./_minio:/data
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: ["/bin/sh","-c"]
    command: >
      "until nc -z minio 9000; do sleep 1; done;
      mc alias set local http://minio:9000 minio minio12345;
      mc mb --ignore-existing local/mlflow || true;
      mc mb --ignore-existing local/dvc || true;"
    networks:
      - default
volumes:
  mlflowdata: {}
  zenmlmysqldata: {}
